name: Run SWAT model on all branches, except main, and store outputs

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  run-swat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SWAT model in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/TxtInOut:/swat_data" \
            -w /swat_data \
            crazyzlj/swat:alpint-2012.683 \
            swat2012.683.gfort.rel

      - name: Collect SWAT outputs
        run: |
          mkdir -p /tmp/swat-output
          cp -r ./TxtInOut/output.snu /tmp/swat-output/
          cp -r ./TxtInOut/output.hru /tmp/swat-output/
          cp -r ./TxtInOut/output.rch /tmp/swat-output/
          cp -r ./TxtInOut/file.cio /tmp/swat-output/
          cd /tmp/swat-output

          [ -f output.snu ] && zip -ur output.zip output.snu
          [ -f output.hru ] && zip -ur output.zip output.hru
          [ -f output.rch ] && zip -ur output.zip output.rch
          [ -f file.cio ] && zip -ur output.zip file.cio

      - name: Checkout output branch
        run: |
          git fetch origin output || true
          TARGET_DIR=${{ github.ref_name }}

          # Make sure we're on the branch that stores results
          if git show-ref --quiet refs/remotes/origin/output; then
            git checkout output
          else
            git checkout --orphan output
            git reset --hard   # clean index state, but don’t mass-delete yet
          fi

          # Remove ONLY the old contents of that folder from git + disk
          git rm -rf --ignore-unmatch $TARGET_DIR

          # Recreate the folder (git rm deletes the dir itself)
          mkdir -p $TARGET_DIR

          # Copy in new generated files
          cp -r /tmp/swat-output/output.zip $TARGET_DIR/

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com)"

          # Stage and commit
          git add $TARGET_DIR
          git commit -m "Model outputs for branch  ${{ github.ref_name }}" || echo "No changes"
          git push origin output
    
